version: "3.2"
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file: ".env"
  server:
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file: ".env"
    depends_on:
      - db
    volumes:
      - ./db/migrations:/Users/root/go/src/testService/db/migrations
    links:
      - db
